package com.rehab.module.schedule;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.rehab.module.order.entity.MedicalOrder;
import com.rehab.module.order.mapper.MedicalOrderMapper;
import com.rehab.module.schedule.entity.PatientSchedule;
import com.rehab.module.schedule.mapper.PatientScheduleMapper;
import com.rehab.module.system.entity.Notification;
import com.rehab.module.system.mapper.NotificationMapper;
import com.rehab.module.task.entity.Task;
import com.rehab.module.task.mapper.TaskMapper;
import com.rehab.module.workload.entity.WorkloadStat;
import com.rehab.module.workload.mapper.WorkloadStatMapper;
import com.rehab.module.auth.entity.User;
import com.rehab.module.auth.mapper.UserMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.YearMonth;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Slf4j
@Component
@RequiredArgsConstructor
public class ScheduledTaskService {

    private final TaskMapper taskMapper;
    private final MedicalOrderMapper medicalOrderMapper;
    private final PatientScheduleMapper patientScheduleMapper;
    private final NotificationMapper notificationMapper;
    private final WorkloadStatMapper workloadStatMapper;
    private final UserMapper userMapper;

    /**
     * Daily reminder at 07:30 — notify therapists with pending tasks for today.
     */
    @Scheduled(cron = "0 30 7 * * ?")
    public void dailyTaskReminder() {
        LocalDate today = LocalDate.now();
        List<Task> pendingTasks = taskMapper.selectList(
                new LambdaQueryWrapper<Task>()
                        .eq(Task::getTaskDate, today)
                        .eq(Task::getStatus, "PENDING")
        );

        Map<Long, List<Task>> tasksByTherapist = pendingTasks.stream()
                .collect(Collectors.groupingBy(Task::getTherapistId));

        int notified = 0;
        for (Map.Entry<Long, List<Task>> entry : tasksByTherapist.entrySet()) {
            Notification n = new Notification();
            n.setUserId(entry.getKey());
            n.setTitle("今日待办提醒");
            n.setContent("您今日有 " + entry.getValue().size() + " 项待处理治疗任务");
            n.setType("TASK");
            n.setIsRead(0);
            notificationMapper.insert(n);
            notified++;
        }

        log.info("Daily task reminder sent: {} therapists notified, {} pending tasks",
                notified, pendingTasks.size());
    }

    /**
     * Monthly workload summary at 02:00 on the 1st of each month.
     */
    @Scheduled(cron = "0 0 2 1 * ?")
    public void monthlyWorkloadSummary() {
        YearMonth lastMonth = YearMonth.now().minusMonths(1);
        LocalDate start = lastMonth.atDay(1);
        LocalDate end = lastMonth.atEndOfMonth();

        List<WorkloadStat> stats = workloadStatMapper.selectList(
                new LambdaQueryWrapper<WorkloadStat>()
                        .between(WorkloadStat::getStatDate, start, end)
        );

        Map<Long, Integer> userTotals = stats.stream()
                .collect(Collectors.groupingBy(WorkloadStat::getUserId,
                        Collectors.summingInt(s -> s.getTreatmentCount() != null ? s.getTreatmentCount() : 0)));

        int notified = 0;
        for (Map.Entry<Long, Integer> entry : userTotals.entrySet()) {
            Notification n = new Notification();
            n.setUserId(entry.getKey());
            n.setTitle(lastMonth.getMonthValue() + "月工作量汇总");
            n.setContent("您上月共完成 " + entry.getValue() + " 项治疗任务");
            n.setType("SYSTEM");
            n.setIsRead(0);
            notificationMapper.insert(n);
            notified++;
        }

        log.info("Monthly workload summary sent for {}: {} users notified", lastMonth, notified);
    }

    /**
     * Auto-generate tasks for today from active approved orders at 06:00 daily.
     */
    @Scheduled(cron = "0 0 6 * * ?")
    @Transactional
    public void autoGenerateDailyTasks() {
        LocalDate today = LocalDate.now();

        // Find approved orders that cover today
        LambdaQueryWrapper<MedicalOrder> orderWrapper = new LambdaQueryWrapper<>();
        orderWrapper.eq(MedicalOrder::getStatus, "APPROVED")
                .le(MedicalOrder::getPeriodStart, today)
                .ge(MedicalOrder::getPeriodEnd, today);
        List<MedicalOrder> activeOrders = medicalOrderMapper.selectList(orderWrapper);

        int totalGenerated = 0;
        for (MedicalOrder order : activeOrders) {
            // Find today's schedule entries for this order
            LambdaQueryWrapper<PatientSchedule> scheduleWrapper = new LambdaQueryWrapper<>();
            scheduleWrapper.eq(PatientSchedule::getSourceId, order.getId())
                    .eq(PatientSchedule::getScheduleDate, today)
                    .eq(PatientSchedule::getEventType, "ORDER")
                    .eq(PatientSchedule::getStatus, "SCHEDULED");
            List<PatientSchedule> schedules = patientScheduleMapper.selectList(scheduleWrapper);

            for (PatientSchedule schedule : schedules) {
                if (taskMapper.existsByOrderAndDateAndSlot(order.getId(), today, schedule.getTimeSlot())) {
                    continue;
                }
                User therapist = schedule.getTherapistId() != null
                        ? userMapper.selectById(schedule.getTherapistId()) : null;

                Task task = new Task();
                task.setPatientId(order.getPatientId());
                task.setOrderId(order.getId());
                task.setTherapistId(schedule.getTherapistId());
                task.setGroupId(therapist != null ? therapist.getGroupId() : null);
                task.setTaskDate(today);
                task.setTimeSlot(schedule.getTimeSlot());
                task.setTreatmentItem(order.getTreatmentItem());
                task.setStatus("PENDING");

                taskMapper.insert(task);
                schedule.setStatus("TASK_GENERATED");
                patientScheduleMapper.updateById(schedule);
                totalGenerated++;
            }
        }

        if (totalGenerated > 0) {
            log.info("Auto-generated {} tasks for today ({})", totalGenerated, today);
        }
    }
}
