USE rehab_db;
DROP TABLE IF EXISTS notification;
CREATE TABLE notification (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    title VARCHAR(255) NOT NULL COMMENT '标题',
    content TEXT DEFAULT NULL COMMENT '内容',
    type VARCHAR(32) NOT NULL COMMENT '类型: TASK/ORDER/SYSTEM',
    is_read TINYINT NOT NULL DEFAULT 0 COMMENT '0=未读, 1=已读',
    source_id BIGINT DEFAULT NULL COMMENT '来源ID',
    is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '软删除',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    INDEX idx_user_read (user_id, is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知消息';
